import { config } from "dotenv";
import { resolve } from "path";
import { getDb } from "@/db";
import { listTypeMaster } from "@/db/schema";

config({ path: resolve(process.cwd(), ".env.local") });

async function seedListTypeMaster() {
  const db = getDb();

  console.log("🌱 リストタイプマスターデータを投入中...");

  // docs/リストタイプ.md の全リストタイプ一覧より (306件)
  const masterData = [
    { listType: "L000", listName: "ﾀﾞﾐｰ", classification14: "00" },
    { listType: "L001", listName: "ﾓｰﾀｰﾘｽﾄ", classification14: "03" },
    { listType: "L002", listName: "ﾎﾟﾝﾌﾟﾘｽﾄ", classification14: "03" },
    { listType: "L003", listName: "真空ﾎﾟﾝﾌﾟﾘｽﾄ", classification14: "03" },
    { listType: "L004", listName: "ﾌﾞﾛﾜｰﾘｽﾄ", classification14: "03" },
    { listType: "L005", listName: "ｺﾝﾌﾟﾚｯｻｰﾘｽﾄ", classification14: "03" },
    { listType: "L006", listName: "ﾌｧﾝﾘｽﾄ", classification14: "03" },
    { listType: "L007", listName: "変減速機ﾘｽﾄ", classification14: "03" },
    { listType: "L008", listName: "攪拌機ﾘｽﾄ", classification14: "03" },
    { listType: "L009", listName: "換気扇ﾘｽﾄ", classification14: "03" },
    { listType: "L010", listName: "遠心脱水機ﾘｽﾄ", classification14: "03" },
    { listType: "L011", listName: "ﾍﾞﾙﾄﾌﾟﾚｽﾘｽﾄ", classification14: "03" },
    { listType: "L012", listName: "ﾌｨﾙﾀｰﾌﾟﾚｽﾘｽﾄ", classification14: "03" },
    { listType: "L013", listName: "ﾄﾞﾗﾑｽｸﾘｰﾝﾘｽﾄ", classification14: "03" },
    { listType: "L014", listName: "ｽｸﾘｭｰﾌﾟﾚｽﾘｽﾄ", classification14: "03" },
    { listType: "L015", listName: "破砕機ﾘｽﾄ", classification14: "03" },
    { listType: "L016", listName: "ﾍﾞﾙﾄｺﾝﾍﾞｱﾘｽﾄ", classification14: "03" },
    { listType: "L017", listName: "ﾁｪｰﾝﾌﾞﾛｯｸﾘｽﾄ", classification14: "03" },
    { listType: "L018", listName: "給水ﾕﾆｯﾄﾘｽﾄ", classification14: "03" },
    { listType: "L019", listName: "ﾄﾞﾚﾝ回収ﾕﾆｯﾄﾘｽﾄ", classification14: "03" },
    { listType: "L020", listName: "ﾁﾗｰﾕﾆｯﾄﾘｽﾄ", classification14: "03" },
    { listType: "L021", listName: "ｽｸﾘｭｰｺﾝﾍﾞｱﾘｽﾄ", classification14: "03" },
    { listType: "L023", listName: "高圧洗浄装置ﾘｽﾄ", classification14: "03" },
    { listType: "L024", listName: "油圧ﾕﾆｯﾄﾘｽﾄ", classification14: "03" },
    { listType: "L025", listName: "ﾌﾗｲﾄｺﾝﾍﾞｱﾘｽﾄ", classification14: "03" },
    { listType: "L026", listName: "その他回転機", classification14: "03" },
    { listType: "L028", listName: "防音ﾎﾞｯｸｽﾘｽﾄ", classification14: "03" },
    { listType: "L029", listName: "防振架台ﾘｽﾄ", classification14: "03" },
    { listType: "L030", listName: "夾雑物除去装置ﾘｽﾄ", classification14: "03" },
    { listType: "L031", listName: "ﾌｨﾙﾀｰﾘｽﾄ", classification14: "03" },
    { listType: "L032", listName: "ｵｰﾄｽﾄﾚｰﾅｰﾘｽﾄ", classification14: "03" },
    { listType: "L033", listName: "ﾗｲﾄﾌｨﾙﾀｰﾘｽﾄ", classification14: "03" },
    { listType: "L034", listName: "B型集毛器ﾘｽﾄ", classification14: "03" },
    { listType: "L035", listName: "ﾐｽﾄｾﾊﾟﾚｰﾀｰﾘｽﾄ", classification14: "03" },
    { listType: "L036", listName: "ｻｲｸﾛﾝﾘｽﾄ", classification14: "03" },
    { listType: "L037", listName: "粗粒分離器ﾘｽﾄ", classification14: "03" },
    { listType: "L038", listName: "ｽｸﾗﾊﾞｰﾘｽﾄ", classification14: "03" },
    { listType: "L039", listName: "その他分離機器", classification14: "03" },
    { listType: "L041", listName: "UV殺菌器ﾘｽﾄ", classification14: "03" },
    { listType: "L042", listName: "低圧UV酸化器ﾘｽﾄ", classification14: "03" },
    { listType: "L043", listName: "高圧UVﾗﾝﾌﾟﾘｽﾄ", classification14: "03" },
    { listType: "L044", listName: "ﾃﾞﾐﾅｰﾘｽﾄ", classification14: "03" },
    { listType: "L045", listName: "除湿器ﾘｽﾄ", classification14: "03" },
    { listType: "L047", listName: "余剰ｶﾞｽ燃焼装置ﾘｽﾄ", classification14: "03" },
    { listType: "L050", listName: "犠牲電極ﾘｽﾄ", classification14: "03" },
    { listType: "L051", listName: "熱交換器ﾘｽﾄ", classification14: "03" },
    { listType: "L052", listName: "ﾋｰﾀｰﾘｽﾄ", classification14: "03" },
    { listType: "L053", listName: "ｽﾁｰﾑｴｾﾞｸﾀｰﾘｽﾄ", classification14: "03" },
    { listType: "L054", listName: "冷却塔ﾘｽﾄ", classification14: "03" },
    { listType: "L056", listName: "蒸留器ﾘｽﾄ", classification14: "01" },
    { listType: "L058", listName: "乾燥機ﾘｽﾄ", classification14: "03" },
    { listType: "L059", listName: "その他化学･熱機器", classification14: "03" },
    { listType: "L061", listName: "ｵｰﾄﾌｨｰﾀﾞｰﾘｽﾄ", classification14: "03" },
    { listType: "L062", listName: "ｸﾘﾌｨｰﾀﾞｰ(KF)ﾘｽﾄ", classification14: "03" },
    { listType: "L063", listName: "ｸﾘﾌｨｰﾀﾞｰ(AFD)ﾘｽﾄ", classification14: "03" },
    { listType: "L070", listName: "ROｱﾀﾞﾌﾟﾀｰﾘｽﾄ", classification14: "03" },
    { listType: "L071", listName: "ﾍﾞｯｾﾙﾘｽﾄ", classification14: "03" },
    { listType: "L072", listName: "樹脂ﾀﾝｸﾘｽﾄ", classification14: "03" },
    { listType: "L073", listName: "ｴｱｰﾀﾝｸﾘｽﾄ", classification14: "03" },
    { listType: "L074", listName: "薬品自動溶解装置ﾘｽﾄ", classification14: "03" },
    { listType: "L075", listName: "ﾎｯﾊﾟｰﾘｽﾄ", classification14: "03" },
    { listType: "L076", listName: "分配計量槽ﾘｽﾄ", classification14: "03" },
    { listType: "L077", listName: "ﾊﾟﾈﾙﾀﾝｸﾘｽﾄ", classification14: "03" },
    { listType: "L078", listName: "ﾍﾞｯｾﾙｸﾗﾝﾌﾟﾘｽﾄ", classification14: "03" },
    { listType: "L079", listName: "その他容器･部品ﾘｽﾄ", classification14: "03" },
    { listType: "L081", listName: "鏡板ﾘｽﾄ", classification14: "03" },
    { listType: "L082", listName: "円筒WWｽｸﾘｰﾝﾘｽﾄ", classification14: "03" },
    { listType: "L083", listName: "ｽﾄﾚｰﾅｰﾘｽﾄ", classification14: "03" },
    { listType: "L084", listName: "ｽﾌﾟﾚｰﾉｽﾞﾙﾘｽﾄ", classification14: "03" },
    { listType: "L085", listName: "ﾃﾞｨﾌｭｰｻﾞｰﾘｽﾄ", classification14: "03" },
    { listType: "L086", listName: "ｵﾘﾌｨｽﾌﾟﾚｰﾄﾘｽﾄ", classification14: "03" },
    { listType: "L087", listName: "ｴｱｰｼﾘﾝﾀﾞｰﾘｽﾄ", classification14: "03" },
    { listType: "L088", listName: "平板WWｽｸﾘｰﾝﾘｽﾄ", classification14: "03" },
    { listType: "L089", listName: "その他製缶部品", classification14: "03" },
    { listType: "L095", listName: "標識ﾘｽﾄ", classification14: "03" },
    { listType: "L096", listName: "洗眼ﾕﾆｯﾄﾘｽﾄ", classification14: "03" },
    { listType: "L097", listName: "ﾁｭｰﾌﾞ･ﾎｰｽﾘｽﾄ", classification14: "03" },
    { listType: "L110", listName: "水中ﾐｷｻｰﾘｽﾄ", classification14: "03" },
    { listType: "L118", listName: "ｵｰﾄﾎﾟﾝﾌﾟﾘｽﾄ", classification14: "03" },
    { listType: "L119", listName: "ﾄﾞﾚﾝ回収ﾎﾟﾝﾌﾟﾘｽﾄ", classification14: "03" },
    { listType: "L121", listName: "流量計ﾘｽﾄ", classification14: "03" },
    { listType: "L122", listName: "圧力計･連成計･真空計ﾘｽﾄ", classification14: "03" },
    { listType: "L123", listName: "温度計ﾘｽﾄ", classification14: "03" },
    { listType: "L124", listName: "液面計ﾘｽﾄ", classification14: "03" },
    { listType: "L125", listName: "圧力計･ｻﾝﾌﾟﾘﾝｸﾞ付属品ﾘｽﾄ", classification14: "03" },
    { listType: "L126", listName: "その他現場計器", classification14: "03" },
    { listType: "L128", listName: "ｹﾞｰｼﾞﾌﾗﾝｼﾞﾘｽﾄ", classification14: "03" },
    { listType: "L129", listName: "ﾌﾛｰﾁｪｯｶｰﾘｽﾄ", classification14: "03" },
    { listType: "L130", listName: "ﾌﾗﾝｼﾞｶﾊﾞｰﾘｽﾄ", classification14: "03" },
    { listType: "L131", listName: "RO･UFｴﾚﾒﾝﾄﾘｽﾄ", classification14: "04" },
    { listType: "L132", listName: "MF膜ﾘｽﾄ", classification14: "04" },
    { listType: "L133", listName: "UF･脱気膜ﾘｽﾄ", classification14: "04" },
    { listType: "L134", listName: "ｲｵﾝ交換樹脂ﾘｽﾄ", classification14: "04" },
    { listType: "L135", listName: "ｺﾝﾃﾞｨｼｮﾆﾝｸﾞﾘｽﾄ", classification14: "04" },
    { listType: "L136", listName: "ろ材ﾘｽﾄ", classification14: "04" },
    { listType: "L137", listName: "寒水石ﾘｽﾄ", classification14: "04" },
    { listType: "L138", listName: "活性炭ﾘｽﾄ", classification14: "04" },
    { listType: "L139", listName: "充填材ﾘｽﾄ", classification14: "04" },
    { listType: "L143", listName: "傾斜板ﾓｼﾞｭｰﾙﾘｽﾄ", classification14: "03" },
    { listType: "L145", listName: "試運転用薬品", classification14: "04" },
    { listType: "L146", listName: "薬品〔土壌浄化〕", classification14: "04" },
    { listType: "L149", listName: "その他充填材", classification14: "04" },
    { listType: "L150", listName: "PVDFﾆｯﾌﾟﾙ(設計手配_在庫割当)ﾘｽﾄ", classification14: "03" },
    { listType: "L151", listName: "自動弁ﾘｽﾄ", classification14: "05" },
    { listType: "L152", listName: "手動弁ﾘｽﾄ", classification14: "05" },
    { listType: "L153", listName: "減圧弁･安全弁ﾘｽﾄ", classification14: "05" },
    { listType: "L154", listName: "定流量弁ﾘｽﾄ", classification14: "05" },
    { listType: "L155", listName: "ﾎﾞｰﾙﾀｯﾌﾟﾘｽﾄ", classification14: "05" },
    { listType: "L156", listName: "LCFﾘｽﾄ", classification14: "03" },
    { listType: "L157", listName: "ﾗｲﾝﾐｷｻｰﾘｽﾄ", classification14: "05" },
    { listType: "L158", listName: "伸縮継手ﾘｽﾄ", classification14: "05" },
    { listType: "L159", listName: "ﾃﾞﾐﾅｰ伸縮継手ﾘｽﾄ", classification14: "05" },
    { listType: "L160", listName: "蒸気吹込ﾉｽﾞﾙ･ｻｲﾚﾝｻｰﾘｽﾄ", classification14: "05" },
    { listType: "L161", listName: "ｳﾞｨｸﾄﾘｯｸｼﾞｮｲﾝﾄﾘｽﾄ", classification14: "05" },
    { listType: "L162", listName: "円錐ｽﾄﾚｰﾅｰﾘｽﾄ", classification14: "05" },
    { listType: "L165", listName: "ｽﾁｰﾑﾄﾗｯﾌﾟﾘｽﾄ", classification14: "05" },
    { listType: "L167", listName: "ｸﾘｰﾝﾍｯﾀﾞｰﾘｽﾄ", classification14: "05" },
    { listType: "L168", listName: "特殊継手ﾘｽﾄ", classification14: "05" },
    { listType: "L169", listName: "その他配管付属品", classification14: "05" },
    { listType: "L173", listName: "膨張ﾀﾝｸﾘｽﾄ", classification14: "03" },
    { listType: "L181", listName: "揮散処理塔〔土壌浄化〕ﾘｽﾄ", classification14: "03" },
    { listType: "L201", listName: "製缶ﾘｽﾄ", classification14: "02" },
    { listType: "L202", listName: "ﾗｲﾆﾝｸﾞﾘｽﾄ", classification14: "02" },
    { listType: "L211", listName: "ｴｾﾞｸﾀｰﾘｽﾄ", classification14: "02" },
    { listType: "L213", listName: "pH計ﾎﾙﾀﾞｰﾘｽﾄ", classification14: "02" },
    { listType: "L214", listName: "散気管･ﾗｲｻﾞｰ管ﾘｽﾄ", classification14: "02" },
    { listType: "L215", listName: "N2ｶﾞｽｼｰﾙﾎﾟｯﾄﾘｽﾄ", classification14: "03" },
    { listType: "L216", listName: "薬品用ｶﾞｽｽｸﾗﾊﾞｰﾘｽﾄ", classification14: "03" },
    { listType: "L217", listName: "医薬用ﾀﾝｸﾘｽﾄ", classification14: "02" },
    { listType: "L218", listName: "ﾛｰﾘｰ受皿ﾘｽﾄ", classification14: "02" },
    { listType: "L219", listName: "ﾄﾞﾗﾑ缶活性炭塔〔土壌浄化〕ﾘｽﾄ", classification14: "03" },
    { listType: "L232", listName: "原水散気管ﾘｽﾄ", classification14: "02" },
    { listType: "L249", listName: "ｸﾞﾚｰﾁﾝｸﾞﾘｽﾄ", classification14: "02" },
    { listType: "L301", listName: "据付配管", classification14: "06" },
    { listType: "L302", listName: "ﾗｲﾆﾝｸﾞ配管", classification14: "06" },
    { listType: "L303", listName: "ﾕｰｽﾎﾟｲﾝﾄ配管", classification14: "06" },
    { listType: "L304", listName: "埋込管･埋込金物ﾘｽﾄ", classification14: "06" },
    { listType: "L305", listName: "配管ﾗｯｸ", classification14: "06" },
    { listType: "L308", listName: "配管材料(ｴｺ工法)", classification14: "06" },
    { listType: "L309", listName: "配管資材ﾘｽﾄ", classification14: "06" },
    { listType: "L400", listName: "運搬費", classification14: "08" },
    { listType: "L401", listName: "塗装工事", classification14: "08" },
    { listType: "L402", listName: "保温工事", classification14: "08" },
    { listType: "L403", listName: "仮設工事", classification14: "08" },
    { listType: "L404", listName: "基礎工事", classification14: "08" },
    { listType: "L405", listName: "埋込管･埋込金物取付工事", classification14: "08" },
    { listType: "L406", listName: "撤去工事", classification14: "08" },
    { listType: "L407", listName: "既設改造工事", classification14: "08" },
    { listType: "L408", listName: "清掃汚泥処理工事", classification14: "08" },
    { listType: "L409", listName: "その他工事", classification14: "08" },
    { listType: "L410", listName: "改造工事①", classification14: "08" },
    { listType: "L411", listName: "改造工事②", classification14: "08" },
    { listType: "L412", listName: "改造工事③", classification14: "08" },
    { listType: "L413", listName: "改造工事④", classification14: "08" },
    { listType: "L414", listName: "改造工事⑤", classification14: "08" },
    { listType: "L415", listName: "改造工事⑥", classification14: "08" },
    { listType: "L416", listName: "改造工事⑦", classification14: "08" },
    { listType: "L417", listName: "改造工事⑧", classification14: "08" },
    { listType: "L418", listName: "改造工事⑨", classification14: "08" },
    { listType: "L419", listName: "改造工事⑩", classification14: "08" },
    { listType: "L420", listName: "輸出梱包･通関費", classification14: "08" },
    { listType: "L421", listName: "海上･航空輸送費", classification14: "08" },
    { listType: "L422", listName: "現地輸送費", classification14: "08" },
    { listType: "L423", listName: "仕向国輸入税(関税)", classification14: "08" },
    { listType: "L424", listName: "組立工事保険", classification14: "08" },
    { listType: "L425", listName: "第三者賠償保険", classification14: "08" },
    { listType: "L426", listName: "ﾒﾝﾃﾅﾝｽ特約保険", classification14: "08" },
    { listType: "L427", listName: "PL保険", classification14: "08" },
    { listType: "L428", listName: "貿易一般保険(経済産業省所管)", classification14: "08" },
    { listType: "L429", listName: "VAT/GST(相手国消費税)増値税", classification14: "08" },
    { listType: "L430", listName: "VAT/GST還付費用", classification14: "08" },
    { listType: "L431", listName: "PE事務所登録費用", classification14: "08" },
    { listType: "L432", listName: "BONDにかかわる費用", classification14: "08" },
    { listType: "L433", listName: "遠隔地輸送費", classification14: "08" },
    { listType: "L441", listName: "諸工事〔土壌浄化〕", classification14: "08" },
    { listType: "L442", listName: "分析〔土壌浄化〕", classification14: "08" },
    { listType: "L443", listName: "井戸工事〔土壌浄化〕", classification14: "08" },
    { listType: "L444", listName: "栄養剤注入工事〔土壌浄化〕", classification14: "08" },
    { listType: "L445", listName: "鉄粉注入工事〔土壌浄化〕", classification14: "08" },
    { listType: "L446", listName: "酸化剤注入工事〔土壌浄化〕", classification14: "08" },
    { listType: "L447", listName: "不溶化剤注入工事〔土壌浄化〕", classification14: "08" },
    { listType: "L448", listName: "その他注入工事〔土壌浄化〕", classification14: "08" },
    { listType: "L449", listName: "測量〔土壌浄化〕", classification14: "08" },
    { listType: "L450", listName: "浄化機器ﾚﾝﾀﾙ〔土壌浄化〕", classification14: "08" },
    { listType: "L451", listName: "予備品", classification14: "09" },
    { listType: "L452", listName: "ﾒﾝﾃ工事〔土壌浄化〕", classification14: "08" },
    { listType: "L461", listName: "予備費", classification14: "09" },
    { listType: "L471", listName: "既設配管切込工事", classification14: "08" },
    { listType: "L472", listName: "雑架台･雑製缶", classification14: "08" },
    { listType: "L473", listName: "RC水槽内配管工事", classification14: "08" },
    { listType: "L474", listName: "RC水槽開口部蓋", classification14: "08" },
    { listType: "L475", listName: "計装空気配管工事", classification14: "08" },
    { listType: "L476", listName: "防音工事", classification14: "08" },
    { listType: "L477", listName: "防振工事", classification14: "08" },
    { listType: "L478", listName: "臭気対策", classification14: "08" },
    { listType: "L479", listName: "土建工事により発生する諸工事", classification14: "08" },
    { listType: "L480", listName: "屋外鉄板養生費", classification14: "08" },
    { listType: "L481", listName: "撤去物処分費", classification14: "08" },
    { listType: "L526", listName: "ｵｿﾞﾝ溶解膜ﾘｽﾄ", classification14: "04" },
    { listType: "L551", listName: "酸化剤〔土壌浄化〕", classification14: "04" },
    { listType: "L552", listName: "不溶化剤〔土壌浄化〕", classification14: "04" },
    { listType: "L553", listName: "鉄粉･還元剤〔土壌浄化〕", classification14: "04" },
    { listType: "L554", listName: "栄養剤〔土壌浄化〕", classification14: "04" },
    { listType: "L590", listName: "井戸枡ﾘｽﾄ", classification14: "03" },
    { listType: "L591", listName: "機器〔土壌浄化〕ﾘｽﾄ", classification14: "03" },
    { listType: "L592", listName: "在庫〔土壌浄化〕", classification14: "03" },
    { listType: "L599", listName: "その他機器ﾘｽﾄ", classification14: "03" },
    { listType: "L612", listName: "酸素ｶﾞｽ濃縮器ﾘｽﾄ", classification14: "03" },
    { listType: "L613", listName: "水素ｶﾞｽ発生器ﾘｽﾄ", classification14: "03" },
    { listType: "L615", listName: "ｵｿﾞﾝｶﾞｽ発生器ﾘｽﾄ", classification14: "03" },
    { listType: "L616", listName: "ﾎﾞｲﾗｰﾘｽﾄ", classification14: "01" },
    { listType: "L626", listName: "ｵｿﾞﾝｶﾞｽ分解ｶﾗﾑﾘｽﾄ", classification14: "01" },
    { listType: "L627", listName: "ｵｿﾞﾝ排水分解ｶﾗﾑﾘｽﾄ", classification14: "01" },
    { listType: "L632", listName: "ｱﾝﾓﾆｱｽﾄﾘｯﾋﾟﾝｸﾞﾘｽﾄ", classification14: "01" },
    { listType: "L651", listName: "ﾋｰﾄﾎﾟﾝﾌﾟﾘｽﾄ", classification14: "03" },
    { listType: "L691", listName: "一括発注機器〔土壌浄化〕", classification14: "01" },
    { listType: "L692", listName: "ﾓﾆﾀﾘﾝｸﾞ〔土壌浄化〕", classification14: "01" },
    { listType: "L693", listName: "ﾌｨﾝｶﾞｰﾌﾟﾘﾝﾄ埋設工事〔土壌浄化〕", classification14: "01" },
    { listType: "L694", listName: "重金属等その他調査工事〔土壌浄化〕", classification14: "01" },
    { listType: "L695", listName: "GEMOL調査〔土壌浄化〕", classification14: "01" },
    { listType: "L696", listName: "浄化試験〔土壌浄化〕", classification14: "01" },
    { listType: "L697", listName: "表層およびｶﾞｽ調査〔土壌浄化〕", classification14: "01" },
    { listType: "L698", listName: "資料等調査〔土壌浄化〕", classification14: "01" },
    { listType: "L699", listName: "その他一括発注機器ﾘｽﾄ", classification14: "01" },
    { listType: "L701", listName: "ﾓｼﾞｭｰﾙ･ｽｷｯﾄﾞ", classification14: "07" },
    { listType: "L702", listName: "ｽｷｯﾄﾞ運搬", classification14: "07" },
    { listType: "L710", listName: "規格商品ﾘｽﾄ", classification14: "07" },
    { listType: "L723", listName: "KCDIﾘｽﾄ", classification14: "07" },
    { listType: "L732", listName: "ﾎｰｽ継手ﾘｽﾄ", classification14: "07" },
    { listType: "L733", listName: "ﾃﾞﾐﾅｰ用ｳﾞｨｸﾄﾘｯｸ短管ﾘｽﾄ", classification14: "07" },
    { listType: "L751", listName: "熱交換器(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L752", listName: "送風機(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L753", listName: "電動機(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L754", listName: "電気ﾋｰﾀｰ(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L755", listName: "ﾎﾟﾝﾌﾟ(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L756", listName: "樹脂ﾀﾝｸ(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L757", listName: "ﾃﾞﾐｽﾀｰ(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L758", listName: "伸縮継手(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L759", listName: "ﾉｽﾞﾙ(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L760", listName: "ﾎｰｽ(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L761", listName: "計器(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L762", listName: "ｺﾝﾌﾟﾚｯｻ(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L763", listName: "ｴｾﾞｸﾀｰ(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L764", listName: "ﾌｨﾙﾀｰﾊｳｼﾞﾝｸﾞ(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L765", listName: "UV装置(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L766", listName: "高圧洗浄機(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L767", listName: "機械加工品(洗浄部門)ﾘｽﾄ", classification14: "02" },
    { listType: "L768", listName: "その他製作品(洗浄部門)ﾘｽﾄ", classification14: "02" },
    { listType: "L769", listName: "制御盤(洗浄部門)ﾘｽﾄ", classification14: "10" },
    { listType: "L770", listName: "ﾌﾟﾛｸﾞﾗﾑ(洗浄部門)ﾘｽﾄ", classification14: "10" },
    { listType: "L771", listName: "その他資機材(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L772", listName: "銘板(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L773", listName: "配管材･継手(洗浄部門)ﾘｽﾄ", classification14: "03" },
    { listType: "L774", listName: "自動弁(洗浄部門)ﾘｽﾄ", classification14: "05" },
    { listType: "L775", listName: "手動弁(洗浄部門)ﾘｽﾄ", classification14: "05" },
    { listType: "L776", listName: "触媒(洗浄部門)ﾘｽﾄ", classification14: "04" },
    { listType: "L777", listName: "充填材(洗浄部門)ﾘｽﾄ", classification14: "04" },
    { listType: "L778", listName: "活性炭(洗浄部門)ﾘｽﾄ", classification14: "04" },
    { listType: "L779", listName: "ｲｵﾝ交換樹脂(洗浄部門)ﾘｽﾄ", classification14: "04" },
    { listType: "L780", listName: "薬品(洗浄部門)", classification14: "04" },
    { listType: "L781", listName: "ｶﾞｽ類(洗浄部門)", classification14: "04" },
    { listType: "L782", listName: "製缶(洗浄部門)ﾘｽﾄ", classification14: "02" },
    { listType: "L783", listName: "試運転･性能確認(洗浄部門)", classification14: "08" },
    { listType: "L784", listName: "配管工事(洗浄部門)", classification14: "08" },
    { listType: "L785", listName: "洗浄工事(洗浄部門)", classification14: "08" },
    { listType: "L786", listName: "JET･ﾌﾞﾗｽﾄ工事(洗浄部門)", classification14: "08" },
    { listType: "L787", listName: "排水･廃液処理工事(洗浄部門)", classification14: "08" },
    { listType: "L788", listName: "産廃処理委託(洗浄部門)", classification14: "08" },
    { listType: "L789", listName: "その他工事(洗浄部門)", classification14: "08" },
    { listType: "L811", listName: "盤ﾘｽﾄ", classification14: "10" },
    { listType: "L821", listName: "ｼｰｹﾝｻﾘｽﾄ", classification14: "10" },
    { listType: "L822", listName: "UPSﾘｽﾄ", classification14: "10" },
    { listType: "L823", listName: "電磁弁ﾘｽﾄ", classification14: "10" },
    { listType: "L827", listName: "ﾀｯﾁﾊﾟﾈﾙﾘｽﾄ", classification14: "10" },
    { listType: "L831", listName: "工業計器ﾘｽﾄ", classification14: "10" },
    { listType: "L841", listName: "検出器ﾘｽﾄ", classification14: "10" },
    { listType: "L852", listName: "ｲﾝﾊﾞｰﾀﾘｽﾄ", classification14: "10" },
    { listType: "L853", listName: "その他電気機器", classification14: "10" },
    { listType: "L854", listName: "直流電源器ﾘｽﾄ", classification14: "10" },
    { listType: "L856", listName: "ｿﾌﾄｽﾀｰﾀｰﾘｽﾄ", classification14: "10" },
    { listType: "L861", listName: "その他付帯設備", classification14: "10" },
    { listType: "L871", listName: "電気計装工事", classification14: "10" },
    { listType: "L892", listName: "ｺﾝﾋﾟｭｰﾀｿﾌﾄ", classification14: "10" },
    { listType: "L900", listName: "土建建築工事", classification14: "11" },
    { listType: "L931", listName: "防食塗装工事①", classification14: "11" },
    { listType: "L971", listName: "廃棄物処分", classification14: "11" },
    { listType: "L972", listName: "汚染土壌収集運搬処分", classification14: "11" },
    { listType: "L973", listName: "DXNs廃棄物収集運搬処分", classification14: "11" },
    { listType: "L974", listName: "石綿廃棄物収集運搬処分", classification14: "11" },
    { listType: "L975", listName: "その他埋設廃棄物収集運搬処分", classification14: "11" },
    { listType: "L991", listName: "土木建築工事〔土壌浄化〕", classification14: "11" },
    { listType: "L992", listName: "掘削除去工事〔DXNs〕", classification14: "11" },
    { listType: "L993", listName: "掘削除去工事〔石綿〕", classification14: "11" },
    { listType: "L994", listName: "掘削除去工事〔その埋設廃棄物〕", classification14: "11" },
    { listType: "L998", listName: "設備購買(機器購入)", classification14: "03" },
    { listType: "L999", listName: "設備購買(工事込)", classification14: "08" },
    { listType: "K121", listName: "KG経費", classification14: "12" },
    { listType: "K131", listName: "機械設計", classification14: "13" },
    { listType: "K132", listName: "ｼｽﾃﾑ制御設計", classification14: "13" },
    { listType: "K133", listName: "土建設計", classification14: "13" },
    { listType: "K141", listName: "M/H(機械)", classification14: "14" },
    { listType: "K142", listName: "M/H(ｼｽﾃﾑ制御)", classification14: "14" },
    { listType: "K143", listName: "M/H(土建)", classification14: "14" },
    { listType: "K144", listName: "M/H(工事･検査)", classification14: "14" },
    { listType: "K145", listName: "M/H(製造管理)", classification14: "14" },
    { listType: "K146", listName: "M/H(開発技術)", classification14: "14" },
  ];

  try {
    console.log("  🧹 既存のマスターデータをクリア中...");
    await db.delete(listTypeMaster);
    console.log("  ✓ クリア完了");

    console.log("  📥 マスターデータ投入中...");
    await db.insert(listTypeMaster).values(masterData);
    console.log(`  ✓ ${masterData.length} 件投入完了`);

    console.log("✅ リストタイプマスターデータの投入が完了しました");
  } catch (error) {
    console.error("❌ エラーが発生しました:", error);
    throw error;
  }
}

seedListTypeMaster()
  .then(() => process.exit(0))
  .catch(() => process.exit(1));
